### ISSUE TITLE
Missing Module ATL

### ISSUE THREAD

**Issue by mbpictures** [yar3333/text-to-speech-ue4#2]
Hi!

Great Plugin, thank you very much!
I ran into an issue, where I couldn't package because the atls.lib weren't add to PublicBuildPath in the build.cs. Adding to it fixed the problem.

Maybe you want to adjust it.

Best regards!

**Comment by freezenification** [comment]
> Hi!
> 
> Great Plugin, thank you very much!
> I ran into an issue, where I couldn't package because the atls.lib weren't add to PublicBuildPath in the build.cs. Adding to it fixed the problem.
> 
> Maybe you want to adjust it.
> 
> Best regards!

Hi, I appreciate this was over two years ago now - but is there any chance you could tell me exactly what to do to add the atls.lib? I'm getting a similar packaging error I believe, but I don't quite know how to fix it and any attempts to edit the build.cs don't seem to work (but it's probably just me doing it wrong since I'm not very technical comparatively).

I'd really like to use this plugin so it'd be a great help if you get a moment! Thanks.
